USE [BetaSql]
GO
/****** Object:  Table [dbo].[ACCION_TH]    Script Date: 16/11/2019 11:47:04 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCION_TH](
	[CODACCION] [varchar](12) NOT NULL,
	[ACCION] [varchar](40) NOT NULL,
	[CODPADRE] [varchar](12) NULL,
	[NIVEL] [numeric](3, 0) NULL,
	[ESGRUPO] [char](1) NOT NULL,
	[CODARBOLFORMATO] [numeric](3, 0) NOT NULL,
 CONSTRAINT [ACCION_THPK] PRIMARY KEY CLUSTERED 
(
	[CODACCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACCIONOBJETO_TH]    Script Date: 16/11/2019 11:47:05 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCIONOBJETO_TH](
	[CODACCION] [varchar](12) NOT NULL,
	[OBJETO] [varchar](40) NOT NULL,
	[PERMISO] [char](1) NOT NULL,
 CONSTRAINT [ACCIONOBJETO_THPK] PRIMARY KEY CLUSTERED 
(
	[CODACCION] ASC,
	[OBJETO] ASC,
	[PERMISO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Conexion_TH]    Script Date: 16/11/2019 11:47:05 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Conexion_TH](
	[CODCONEXION] [nvarchar](100) NOT NULL,
	[CADENACONEXION] [nvarchar](400) NOT NULL,
	[USUARIOBD] [nvarchar](100) NOT NULL,
	[CLAVEBD] [nvarchar](200) NOT NULL,
	[TIPOBD] [numeric](2, 0) NOT NULL,
	[PROVEEDORBD] [numeric](2, 0) NOT NULL,
	[ACTIVA] [nvarchar](2) NOT NULL,
	[CADENACONEXIONRPT] [nvarchar](1000) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLEADO_TPP]    Script Date: 16/11/2019 11:47:05 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADO_TPP](
	[CODEMPLEADO] [numeric](10, 0) NOT NULL,
	[NOMBRE1] [varchar](30) NOT NULL,
	[NOMBRE2] [varchar](30) NULL,
	[APELLIDO1] [varchar](30) NOT NULL,
	[APELLIDO2] [varchar](30) NULL,
	[CODPROFESION] [numeric](10, 0) NOT NULL,
	[DIRECCION] [varchar](250) NOT NULL,
	[TELEFONO] [varchar](50) NULL,
	[SEXO] [char](1) NOT NULL,
	[LIBRETA] [varchar](15) NULL,
	[DISTRITO] [varchar](3) NULL,
	[CODESTADOCIVIL] [numeric](2, 0) NOT NULL,
	[NUMDOCUMENTO] [varchar](15) NOT NULL,
	[CODESTADOEMPLEADO] [numeric](2, 0) NOT NULL,
	[FECHANACIMIENTO] [datetime] NOT NULL,
	[CODCIUDADNACIMIENTO] [numeric](10, 0) NOT NULL,
	[CODTIPODOCUMENTO] [numeric](2, 0) NOT NULL,
	[LIBRETACLASE] [varchar](2) NULL,
	[CODCIUDADRESIDENCIA] [numeric](10, 0) NOT NULL,
	[GRUPOSANGUINEO] [varchar](4) NOT NULL,
	[CODCIUDADEXPEDICION] [numeric](10, 0) NULL,
	[CODACCESOGRUPO] [numeric](3, 0) NULL,
	[FECHACAMBIO] [datetime] NULL,
	[FECHAINSERCION] [datetime] NOT NULL,
	[CODPAISNACIONALIDAD] [numeric](10, 0) NOT NULL,
	[EMAIL] [varchar](80) NULL,
	[CODNIVELEDUCACION] [numeric](2, 0) NULL,
	[CODETNIA] [numeric](3, 0) NOT NULL,
	[CLAVE] [varchar](70) NULL,
	[ACTIVO] [char](1) NOT NULL,
	[CAMBIAR] [char](1) NOT NULL,
	[USUARIOLDAP] [varchar](255) NULL,
	[CODALTERNO] [varchar](14) NULL,
	[MOVIL] [varchar](10) NULL,
	[HABILITADOPARALIBRANZA] [char](1) NULL,
	[FECHAAUTORIZACIONLIBRANZA] [datetime] NULL,
	[FECHAEXPDOCUMENTO] [date] NULL,
	[CODDIRECCION] [numeric](10, 0) NULL,
 CONSTRAINT [EMPLEADO_TPPPK] PRIMARY KEY CLUSTERED 
(
	[CODEMPLEADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MENUWEB_TH]    Script Date: 16/11/2019 11:47:05 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MENUWEB_TH](
	[CODMENUWEB] [varchar](10) NOT NULL,
	[MENUWEB] [varchar](50) NULL,
	[IMGNORMAL] [varchar](255) NULL,
	[IMGCANDIDATO] [varchar](255) NULL,
	[IMGSELECCIONADO] [varchar](255) NULL,
	[EXPANDIBLE] [char](1) NOT NULL,
	[CODMENUWEBPADRE] [varchar](10) NULL,
	[URL] [varchar](255) NULL,
	[ORDEN] [varchar](10) NOT NULL,
	[NIVEL] [numeric](1, 0) NOT NULL,
	[ACTIVO] [char](1) NOT NULL,
	[TIP] [varchar](255) NULL,
	[MODULO] [varchar](2) NOT NULL,
	[OBJETO] [varchar](40) NULL,
	[PERMISO] [char](1) NULL,
	[ESPROCESO] [varchar](1) NULL,
	[CODMENUWEBPADREPROCESO] [varchar](10) NULL,
	[ICONO] [varchar](50) NULL,
 CONSTRAINT [PK_MENUWEB_TH] PRIMARY KEY CLUSTERED 
(
	[CODMENUWEB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROL_TH]    Script Date: 16/11/2019 11:47:05 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROL_TH](
	[ROL] [varchar](20) NOT NULL,
	[DESCRIPCIONROL] [varchar](50) NOT NULL,
 CONSTRAINT [ROL_THPK] PRIMARY KEY CLUSTERED 
(
	[ROL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLACCION_TH]    Script Date: 16/11/2019 11:47:05 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLACCION_TH](
	[ROL] [varchar](20) NOT NULL,
	[CODACCION] [varchar](12) NOT NULL,
 CONSTRAINT [ROLACCION_THPK] PRIMARY KEY CLUSTERED 
(
	[ROL] ASC,
	[CODACCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCION_TH] ADD  DEFAULT ((0)) FOR [NIVEL]
GO
ALTER TABLE [dbo].[ACCION_TH] ADD  DEFAULT ('N') FOR [ESGRUPO]
GO
ALTER TABLE [dbo].[ACCION_TH] ADD  DEFAULT ((1)) FOR [CODARBOLFORMATO]
GO
ALTER TABLE [dbo].[MENUWEB_TH] ADD  CONSTRAINT [DF__MENUWEB_T__MODUL__0CBAE877]  DEFAULT ('HG') FOR [MODULO]
GO
ALTER TABLE [dbo].[ACCION_TH]  WITH NOCHECK ADD  CONSTRAINT [FK_ACCION_TH_ARBOLFORMATO_TH] FOREIGN KEY([CODARBOLFORMATO])
REFERENCES [dbo].[ARBOLFORMATO_TH] ([CODARBOLFORMATO])
GO
ALTER TABLE [dbo].[ACCION_TH] CHECK CONSTRAINT [FK_ACCION_TH_ARBOLFORMATO_TH]
GO
ALTER TABLE [dbo].[ACCIONOBJETO_TH]  WITH CHECK ADD  CONSTRAINT [FK_ACCIONOBJETO_TH_ACCION_TH] FOREIGN KEY([CODACCION])
REFERENCES [dbo].[ACCION_TH] ([CODACCION])
GO
ALTER TABLE [dbo].[ACCIONOBJETO_TH] CHECK CONSTRAINT [FK_ACCIONOBJETO_TH_ACCION_TH]
GO
ALTER TABLE [dbo].[EMPLEADO_TPP]  WITH NOCHECK ADD  CONSTRAINT [FK_EMPLEADO_TPP_ACCESOGRUPO_TH] FOREIGN KEY([CODACCESOGRUPO])
REFERENCES [dbo].[ACCESOGRUPO_TH] ([CODACCESOGRUPO])
GO
ALTER TABLE [dbo].[EMPLEADO_TPP] CHECK CONSTRAINT [FK_EMPLEADO_TPP_ACCESOGRUPO_TH]
GO
ALTER TABLE [dbo].[EMPLEADO_TPP]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_TPP_DIRECCION_TH] FOREIGN KEY([CODDIRECCION])
REFERENCES [dbo].[DIRECCION_TH] ([CODDIRECCION])
GO
ALTER TABLE [dbo].[EMPLEADO_TPP] CHECK CONSTRAINT [FK_EMPLEADO_TPP_DIRECCION_TH]
GO
ALTER TABLE [dbo].[EMPLEADO_TPP]  WITH NOCHECK ADD  CONSTRAINT [FK_EMPLEADO_TPP_ESTADOEMPLEADO] FOREIGN KEY([CODESTADOEMPLEADO])
REFERENCES [dbo].[ESTADOEMPLEADO_TPP] ([CODESTADOEMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADO_TPP] CHECK CONSTRAINT [FK_EMPLEADO_TPP_ESTADOEMPLEADO]
GO
ALTER TABLE [dbo].[ROLACCION_TH]  WITH NOCHECK ADD  CONSTRAINT [FK_ROLACCION_TH_ROL_TH] FOREIGN KEY([ROL])
REFERENCES [dbo].[ROL_TH] ([ROL])
GO
ALTER TABLE [dbo].[ROLACCION_TH] CHECK CONSTRAINT [FK_ROLACCION_TH_ROL_TH]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Fecha de Expedicion del documento' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLEADO_TPP', @level2type=N'COLUMN',@level2name=N'FECHAEXPDOCUMENTO'
GO
